export { dadosImoveis };

var dadosImoveis = [

    {   link:"praca-omaguas-pinheiros",
        foto:"/images/imoveis/praca-omaguas-pinheiros/foto-card.jpg",
        nome:"Praça Omaguás Pinheiros",
        status:"obras",
        local:"Pinheiros - São Paulo",
        zona:"zo",
        dados:"Suítes e Duplex",
        detalhes:"Aptos. 128m² a 166m² - 2 a 3 Suítes | Duplex 252m² a 325m² - 3 a 4 Suítes",
        vagas:"2 a 4 vagas",
        regiao: "Pinheiros",
        endereco: "Praça dos Omaguás",
        qtd: 24,
        plantas: 7
    }
    ,{  link:"the-collection-madalena",
        foto:"/images/imoveis/the-collection-madalena/foto-card.jpg",
        nome:"The Collection Madalena",
        status:"obras",
        local:"Perdizes - São Paulo",
        zona:"zo",
        dados:"Aptos. e Studios",
        detalhes:"Suíte 37m² | Studio 26m²",
        vagas:"",
        regiao: "Perdizes",
        endereco: "Rua Valdir Niemeyer",
        qtd: 17,
        plantas: 2
    }
    ,{  link:"boreal-madalena",
        foto:"/images/imoveis/boreal-madalena/foto-card.jpg",
        nome:"Boreal Madalena",
        status:"obras",
        local:"Pompéia - São Paulo",
        zona:"zo",
        dados:"Aptos. com até 2 Suítes",
        detalhes:"50m² e 76m²",
        vagas:"1 vaga",
        regiao: "Pompéia",
        endereco: "Avenida Pompéia",
        qtd: 20,
        plantas: 2
    }
    ,{  link:"the-collection-moema",
        foto:"/images/imoveis/the-collection-moema/foto-card.jpg",
        nome:"The Collection Moema",
        status:"planta",
        local:"Moema - São Paulo",
        zona:"zs",
        dados:"Studios e 1 Dormitório",
        detalhes:"26m² a 37m²",
        vagas:"",
        regiao: "Moema",
        endereco: "Alameda Jauaperi",
        qtd: 23,
        plantas: 6
    }
    ,{  link:"side-ipiranga",
        foto:"/images/imoveis/side-ipiranga/foto-card.jpg",
        nome:"Side Ipiranga",
        status:"pronto",
        local:"Ipiranga - São Paulo",
        zona:"zs",
        dados:"2 a 3 Dormitórios",
        detalhes:"52m² - 2 Dormitórios | 72m² - 3 Dormitórios",
        vagas:"1 vaga",
        regiao: "Ipiranga",
        endereco: "Rua do Lago",
        qtd: 13,
        plantas: 2
    }
    ,{  link:"vista-campo-belo",
        foto:"/images/imoveis/vista-campo-belo/foto-card.jpg",
        nome:"Vista Campo Belo",
        status:"obras",
        local:"Campo Belo - São Paulo",
        zona:"zs",
        dados:"2 a 3 Suítes",
        detalhes:"77m² - 2 Suítes e 1 vaga | 131m² - 3 Suítes e 2 vagas",
        vagas:"1 a 2 vagas",
        regiao: "Campo Belo",
        endereco: "Avenida Vereador José Diniz",
        qtd: 17,
        plantas: 2
    }
    ,{  link:"athos-paraiso",
        foto:"/images/imoveis/athos-paraiso/foto-card.jpg",
        nome:"Athos Paraíso",
        status:"pronto",
        local:"Paraíso - São Paulo",
        zona:"zs",
        dados:"Aptos. com 3 Suítes",
        detalhes:"156m² - 3 Suítes",
        vagas:"2 ou 3 vagas",
        regiao: "Paraíso",
        endereco: "Rua Rafael de Barros",
        qtd: 22,
        plantas: 1
    }
    ,{  link:"the-collection-paulista",
        foto:"/images/imoveis/the-collection-paulista/foto-card.jpg",
        nome:"The Collection Paulista",
        status:"obras",
        local:"Bela Vista - São Paulo",
        zona:"zo",
        dados:"Studios 1 ou 2 Dormitórios",
        detalhes:"26m² a 60m²",
        vagas:"",
        regiao: "Bela Vista",
        endereco: "Rua Almirante Marques de Leão",
        qtd: 23,
        plantas: 4
    }
    ,{  link:"arky-cayowaa",
        foto:"/images/imoveis/arky-cayowaa/foto-card.jpg",
        nome:"Arky Cayowaá",
        status:"pronto",
        local:"Perdizes - São Paulo",
        zona:"zo",
        dados:"1 a 2 Suítes ou 3 Dormitórios",
        detalhes:"51m² - 1 Suíte | 80m² - 2 Suítes | 102m² - 3 Dormitórios",
        vagas:"1 a 2 vagas",
        regiao: "Perdizes",
        endereco: "Rua Cayowaà",
        qtd: 13,
        plantas: 3
    }
    ,{  link:"side-sacoma",
        foto:"/images/imoveis/side-sacoma/foto-card.jpg",
        nome:"Side Sacomã",
        status:"planta",
        local:"Ipiranga - São Paulo",
        zona:"zs",
        dados:"2 a 3 Dormitórios (1 Suíte)",
        detalhes:"36m² a 65m²",
        vagas:"1 vaga",
        regiao: "Ipiranga",
        endereco: "Rua do Lago",
        qtd: 29,
        plantas: 7
    }
    ,{  link:"mirant-ibirapuera",
        foto:"/images/imoveis/mirant-ibirapuera/foto-card.jpg",
        nome:"Mirant Ibirapuera",
        status:"obras",
        local:"Vila Clementino - São Paulo",
        zona:"zs",
        dados:"2 a 4 Suítes",
        detalhes:"112m² 3 Dorms. 2 Suítes | 142m² e 151m² 4 Dorms. 2 Suítes | 178m² 4 Suítes",
        vagas:"2 a 3 vagas",
        regiao: "Vila Clementino",
        endereco: "Rua Pedro de Toledo",
        qtd: 21,
        plantas: 3
    }
    ,{  link:"peninsula-vila-madalena",
        foto:"/images/imoveis/peninsula-vila-madalena/foto-card.jpg",
        nome:"Península Vila Madalena",
        status:"obras",
        local:"Vila Madalena - São Paulo",
        zona:"zo",
        dados:"Suítes e Duplex",
        detalhes:"154m² ou 193m² 3 ou 4 Suítes | Duplex 300m² ou 374m² 3 ou 4 Suítes",
        vagas:"2 a 3 vagas",
        regiao: "Vila Madalena",
        endereco: "Rua João Moura",
        qtd: 25,
        plantas: 5
    }

    /*
    ,{  link:"{link-do-imovel}",
        foto:"/images/imoveis/{link-do-imovel}/foto-card.jpg",
        nome:"",
        status:"{pronto|obras|planta}",
        local:"",
        zona:"{zs|zo}",
        dados:"",
        detalhes:"",
        vagas:"",
        regiao: "",
        endereco: "",
        qtd: 0,
        plantas: 0
    }
    */
];