export { descricoesFotos };

var descricoesFotos = [

    {   link:"praca-omaguas-pinheiros",
        descricoes: [
            "Detalhe Fachada",
            "Praça de Entrada",
            "Acesso",
            "Piscina",
            "Piscina",
            "Piscina Coberta",
            "Sauna Seca",
            "Sala de Massagem",
            "Quadra Recreativa de Areia",
            "Espaço Jogos",
            "Salão de Festas com Gourmet",
            "Lounge Boutique",
            "Fitness",
            "Brinquedoteca",
            "Playground com Lounge Integrado",
            "Coworking",
            "Bicicletário",
            "Espaço Mini Market",
            "Central Delivery",
            "Hall de Entrada",
            "Apartamento Duplex Superior de 325m²",
            "Living Ampliado do Apartamento de 128 m²",
            "Apartamento Duplex Superior de 252m²",
            "Living do Apartamento Decorado de 166m²"
        ]
    }
    ,{  link:"the-collection-madalena",
        descricoes: [
            "Piscina e Bangalôs",
            "Embasamento",
            "Pool Bar e Lounge Externo",
            "Piscina e Solarium - Vista Aérea",
            "Praça das Jabuticabeiras e Fitness",
            "Coworking",
            "Churrasqueira e Forno de Pizza",
            "Salão de Festas",
            "Salão de Festas",
            "Bicicletário",
            "Espaço Lareira",
            "Espaço Pet",
            "Lavanderia Coletiva",
            "Lobby",
            "Living - 1 Dormitório - 37m²",
            "Living Studio - 26m²",
            "Living Studio - 26m²"
        ]
    }
    ,{  link:"boreal-madalena",
        descricoes: [
            "Detalhe Fachada",
            "Vista Aérea",
            "Portaria",
            "Piscina",
            "Bar Piscina",
            "Fitness",
            "Fitness",
            "Quadra de Squash",
            "Sauna",
            "Lobby",
            "Espaço Gourmet",
            "Churrasqueira",
            "Sala de Jogos",
            "Brinquedoteca",
            "Brinquedoteca",
            "Boulevard de Entrada",
            "Boulevard de Entrada",
            "Lavanderia",
            "Living - 2 Suítes",
            "Living - 1 Suíte"
        ]
    }
    ,{  link:"the-collection-moema",
        descricoes: [
            "Embasamento - Alameda Jauaperi",
            "Cobertura Lazer",
            "Sky Bar",
            "Churrasqueira com Forno de Pizza",
            "Espaço Lareira",
            "Piscina com Bangalô",
            "Piscina com Raia e Deck molhado",
            "Lazer na Cobertura",
            "Lounge",
            "Salão de Festas com Gourmet",
            "Fitness",
            "Fitness",
            "Espaço Yoga",
            "Coworking",
            "Bicicletário",
            "Espaço Pet",
            "Espaço para Mini Market",
            "Central Delivery",
            "Lavanderia Coletiva",
            "Lobby",
            "Escada estilizada",
            "Unidade de 1 Dorm. - Final 13 - Decorado",
            "Unidade Studio - Final 11"
        ]
    }
    ,{  link:"side-ipiranga",
        descricoes: [
            "Portaria",
            "Boulevard",
            "Piscina Adulto",
            "Piscina Infantil",
            "Piscina Infantil",
            "Quadra Recreativa",
            "Fitness",
            "Salão de Festas",
            "Espaço Gourmet",
            "Churrasqueira",
            "Coworking",
            "Redário",
            "Living - 3 Dormitórios"
        ]
    }
    ,{  link:"vista-campo-belo",
        descricoes: [
            "Fachada com Vista Livre",
            "Embasamento - Portaria",
            "Piscina Coberta",
            "Fitness",
            "Fitness",
            "Espaço Yoga",
            "Lobby Acesso Elevadores",
            "Churrasqueira",
            "Salão de Festas",
            "Salão de Jogos",
            "Brinquedoteca",
            "Pet Place",
            "Central Delivery",
            "Bicicletário",
            "Corredor",
            "Living - 3 Suítes",
            "Living - 2 Suítes"
        ]
    }
    ,{  link:"athos-paraiso",
        descricoes: [
            "Portaria",
            "Portaria",
            "Fachada",
            "Deck molhado",
            "Piscina",
            "Vista Piscina - Cobertura",
            "Sauna e Ducha",
            "Sala de Masssagem",
            "Sala de Descanso",
            "Sala de Descanso",
            "Área Gourmet",
            "Salão de Festas",
            "Salão de Festas - Detalhes",
            "Fitness",
            "Fitness",
            "Brinquedoteca",
            "Hall Social",
            "Hall Social",
            "Praça",
            "Living",
            "Living Integrado",
            "Suíte Master"
        ]
    }
    ,{  link:"the-collection-paulista",
        descricoes: [
            "Piscina",
            "Fachada",
            "Cinema",
            "Fitness",
            "Sky",
            "Sky",
            "Bicicletário",
            "Espaço Luau",
            "Coworking Studios",
            "Churrasqueira",
            "Pet Place",
            "Praça Coworking",
            "Lounge de Festas",
            "Salão de Festas",
            "Lavanderia",
            "Lobby Torre A",
            "Delivery Torre A",
            "Lobby Torre B",
            "Delivery Torre B",
            "Portaria Torre B",
            "Coworking",
            "Living 36m²",
            "Living 25m²"
        ]
    }
    ,{  link:"arky-cayowaa",
        descricoes: [
            "Churrasqueira",
            "Piscina",
            "Fitness",
            "Web Lounge",
            "Sky Deck",
            "Salão de Festas",
            "Brinquedoteca",
            "Bicicletário",
            "Salão de Jogos",
            "Espaço Pet",
            "Redário",
            "Playground",
            "Lavanderia"
        ]
    }
    ,{  link:"side-sacoma",
        descricoes: [
            "Portaria",
            "Piscina",
            "Piscina Adulto e Infantil",
            "Brinquedoteca - Apoio Piscina",
            "Quadra Recreativa de Areia",
            "Espaço Luau e Quadra Recreativa",
            "Churrasqueira",
            "Churrasqueira Térreo",
            "Churrasqueira Subsolo",
            "Sports Bar",
            "Salão de Festas",
            "Apoio Salão de Festas",
            "Sala de Jogos",
            "Espaço bem-estar",
            "Atelier",
            "Fitness",
            "Fitness",
            "Coworking",
            "Coworking",
            "Coworking",
            "Playground",
            "Playground Baby",
            "Horta",
            "Lavanderia Coletiva Omo",
            "Mini Mercado",
            "Delivery",
            "Living do Apto. de 65m² - Decorado",
            "Suíte Master do Apto. de 65m² - Decorado",
            "Living do Apto. de 40m²"
        ]
    }
    ,{  link:"mirant-ibirapuera",
        descricoes: [
            "Detalhe Cobertura",
            "Embasamento",
            "Churrasqueira",
            "Terraço - Cobertura",
            "Vista Aérea da Área de Lazer",
            "Piscina e Solarium",
            "Lounge Externo",
            "Lounge Descoberto",
            "Salão de Festas",
            "Gourmet",
            "Fitness",
            "Pet Place",
            "Brinquedoteca",
            "Playground",
            "Bicicletário",
            "Coworking",
            "Delivery",
            "Praça Alameda - Acesso",
            "Living 178m²",
            "Suíte 178m² - Decorado",
            "Living 112m²"
        ]
    }
    ,{  link:"peninsula-vila-madalena",
        descricoes: [
            "Lounge Externo",
            "Acesso Residencial",
            "Piscina",
            "Vista Aérea do Complexo da Piscina",
            "Piscina Coberta com Raia de 25m",
            "Salão de Festas",
            "Bicicletário",
            "Fitness",
            "Fitness",
            "Bangalô",
            "Sauna Seca",
            "Quadra de Areia",
            "Pet Place",
            "Gourmet",
            "Brinquedoteca",
            "Playground",
            "Delivery",
            "Sports Bar",
            "Sala de luta",
            "Pilates",
            "Sala de Jogos",
            "Terraço/Living - Duplex 3 Suítes 300m²",
            "Terraço Descoberto - Duplex 4 Suítes 374m²",
            "Living - Apto. 193m² - Decorado",
            "Suíte Master - Apto. 193m² - Decorado"
        ]
    }

    /*
    ,{  link:"{link-do-imovel}",
        descricoes: [
            "",
            ""
        ]
    }
    */
];